Part 1

We are working on a winter weather risk severity index with respect to disruptions to daily life for the January 25-26 winter storm based on the amount of snow, sleet, wind, and ice accretion.

We want to explore this kind of index because large snow, sleet, and particularly ice accumulations, coupled with gusty winds can lead to significant disruptions to daily life with heavily decreased visibilities and a high number of power outages over a large area, especially during the 1/25-26/2026 winter storm which covered most of the eastern US and delivered a wide swath of 12+ inch snow totals and high sleet and ice accretion.

Anyone in the general public, especially emergency management operators, can use this index because this index will highlight residential and transportation impacts.

In [47]:
from herbie import Herbie, FastHerbie
import pandas as pd, numpy as np
import xarray as xr
import dask

In [48]:
run = pd.Timestamp("2026-01-23-00")

In [49]:
# model run Jan 23 2026
H = Herbie(run, model="ifs", product="oper", fxx=6, save_dir='./courses/meteo473/sp26/group6/data/', overwrite=True)

✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Jan-23 00:00 UTC F06 ┊ GRIB2 @ google ┊ IDX @ google

In [50]:
H.inventory()

Downloading inventory file from self.idx='https://storage.googleapis.com/ecmwf-open-data/20260123/00z/ifs/0p25/oper/20260123000000-6h-oper-fc.index'

,grib_message,start_byte,end_byte,range,reference_time,valid_time,step,param,levelist,levtype,number,domain,expver,class,type,stream,search_this
0,1,0,187781,0-187781,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,lsm,NaN,sfc,NaN,g,0001,od,fc,oper,:lsm:sfc:g:0001:od:fc:oper
1,2,187781,311855,187781-311855,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,asn,NaN,sfc,NaN,g,0001,od,fc,oper,:asn:sfc:g:0001:od:fc:oper
2,3,311855,970138,311855-970138,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,tcwv,NaN,sfc,NaN,g,0001,od,fc,oper,:tcwv:sfc:g:0001:od:fc:oper
3,4,970138,1545571,970138-1545571,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,q,150,pl,NaN,g,0001,od,fc,oper,:q:150:pl:g:0001:od:fc:oper
4,5,1545571,2026808,1545571-2026808,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,vsw,1,sol,NaN,g,0001,od,fc,oper,:vsw:1:sol:g:0001:od:fc:oper
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
155,156,122734816,123456734,122734816-123456734,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,700,pl,NaN,g,0001,od,fc,oper,:v:700:pl:g:0001:od:fc:oper
156,157,123456734,124157221,123456734-124157221,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,700,pl,NaN,g,0001,od,fc,oper,:u:700:pl:g:0001:od:fc:oper
157,158,124157221,124601968,124157221-124601968,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,150,pl,NaN,g,0001,od,fc,oper,:gh:150:pl:g:0001:od:fc:oper
158,159,124601968,125964113,124601968-125964113,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,d,400,pl,NaN,g,0001,od,fc,oper,:d:400:pl:g:0001:od:fc:oper
159,160,125964113,126569022,125964113-126569022,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,150,pl,NaN,g,0001,od,fc,oper,:t:150:pl:g:0001:od:fc:oper

In [51]:
run

Timestamp('2026-01-23 00:00:00')

In [52]:
H = Herbie(run, model="ifs", product="oper", fxx=6, save_dir='./data/', overwrite=True)

✅ Found ┊ model=ifs ┊ product=oper ┊ 2026-Jan-23 00:00 UTC F06 ┊ GRIB2 @ google ┊ IDX @ google

In [53]:
H.inventory

<bound method Herbie.inventory of ▌▌Herbie IFS model oper product initialized 2026-Jan-23 00:00 UTC F06 ┊ source=google>

In [54]:
# specific parameters: geopotential height, 2m temp, snow depth (m), wind chill, wind speed, u and v components, visibility, total precipitation
#
ss = r":(gh|t|u|v|2t|sd|10fg|sp|ws|tp|ptype):"

In [55]:
H.inventory().param.unique()

Downloading inventory file from self.idx='https://storage.googleapis.com/ecmwf-open-data/20260123/00z/ifs/0p25/oper/20260123000000-6h-oper-fc.index'

array(['lsm', 'asn', 'tcwv', 'q', 'vsw', 'sithick', 'sot', 'strd', 'ssr',
       'str', 'ttr', '10fg', 'gh', 'ewss', 'w', 'nsss', 'r', 'vo', 't',
       'u', 'v', 'd', 'ro', 'tp', 'sd', 'sf', 'mx2t3', 'msl', 'mn2t3',
       'sve', 'svn', 'mucape', '100u', 'zos', '100v', 'tcc', 'skt', '10u',
       '10v', 'ptype', '2t', 'tprate', '2d', 'ssrd', 'sp', 'tcw'],
      dtype=object)

In [56]:
H.inventory(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,step,param,levelist,levtype,number,domain,expver,class,type,stream,search_this
14,15,9236387,10654672,9236387-10654672,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,10fg,NaN,sfc,NaN,g,0001,od,fc,oper,:10fg:sfc:g:0001:od:fc:oper
15,16,10654672,11139448,10654672-11139448,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,850,pl,NaN,g,0001,od,fc,oper,:gh:850:pl:g:0001:od:fc:oper
21,22,14954263,15544525,14954263-15544525,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,850,pl,NaN,g,0001,od,fc,oper,:t:850:pl:g:0001:od:fc:oper
22,23,15544525,15968866,15544525-15968866,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,100,pl,NaN,g,0001,od,fc,oper,:gh:100:pl:g:0001:od:fc:oper
23,24,15968866,16677673,15968866-16677673,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,500,pl,NaN,g,0001,od,fc,oper,:u:500:pl:g:0001:od:fc:oper
25,26,17301520,18036390,17301520-18036390,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,500,pl,NaN,g,0001,od,fc,oper,:v:500:pl:g:0001:od:fc:oper
30,31,21638665,22261128,21638665-22261128,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,100,pl,NaN,g,0001,od,fc,oper,:t:100:pl:g:0001:od:fc:oper
31,32,22261128,23021073,22261128-23021073,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,400,pl,NaN,g,0001,od,fc,oper,:v:400:pl:g:0001:od:fc:oper
32,33,23021073,23700472,23021073-23700472,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,tp,NaN,sfc,NaN,g,0001,od,fc,oper,:tp:sfc:g:0001:od:fc:oper
35,36,26267824,26996785,26267824-26996785,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,400,pl,NaN,g,0001,od,fc,oper,:u:400:pl:g:0001:od:fc:oper
36,37,26996785,27186152,26996785-27186152,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,sd,NaN,sfc,NaN,g,0001,od,fc,oper,:sd:sfc:g:0001:od:fc:oper
37,38,27186152,27683294,27186152-27683294,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,600,pl,NaN,g,0001,od,fc,oper,:gh:600:pl:g:0001:od:fc:oper
44,45,31264866,31654746,31264866-31654746,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,50,pl,NaN,g,0001,od,fc,oper,:gh:50:pl:g:0001:od:fc:oper
46,47,32176555,32808640,32176555-32808640,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,600,pl,NaN,g,0001,od,fc,oper,:t:600:pl:g:0001:od:fc:oper
49,50,34673712,35275273,34673712-35275273,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,250,pl,NaN,g,0001,od,fc,oper,:u:250:pl:g:0001:od:fc:oper
51,52,36225848,36850405,36225848-36850405,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,250,pl,NaN,g,0001,od,fc,oper,:v:250:pl:g:0001:od:fc:oper
56,57,41106694,41787941,41106694-41787941,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,150,pl,NaN,g,0001,od,fc,oper,:u:150:pl:g:0001:od:fc:oper
57,58,41787941,42422185,41787941-42422185,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,50,pl,NaN,g,0001,od,fc,oper,:t:50:pl:g:0001:od:fc:oper
59,60,43201396,43884993,43201396-43884993,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,150,pl,NaN,g,0001,od,fc,oper,:v:150:pl:g:0001:od:fc:oper
63,64,46881918,47342394,46881918-47342394,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,300,pl,NaN,g,0001,od,fc,oper,:gh:300:pl:g:0001:od:fc:oper
69,70,51888216,52343312,51888216-52343312,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,200,pl,NaN,g,0001,od,fc,oper,:gh:200:pl:g:0001:od:fc:oper
74,75,55722309,56325831,55722309-56325831,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,300,pl,NaN,g,0001,od,fc,oper,:t:300:pl:g:0001:od:fc:oper
75,76,56325831,57068338,56325831-57068338,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,850,pl,NaN,g,0001,od,fc,oper,:v:850:pl:g:0001:od:fc:oper
77,78,57937533,58659399,57937533-58659399,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,850,pl,NaN,g,0001,od,fc,oper,:u:850:pl:g:0001:od:fc:oper
82,83,62390421,63005260,62390421-63005260,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,200,pl,NaN,g,0001,od,fc,oper,:t:200:pl:g:0001:od:fc:oper
84,85,63868219,64877643,63868219-64877643,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,ptype,NaN,sfc,NaN,g,0001,od,fc,oper,:ptype:sfc:g:0001:od:fc:oper
85,86,64877643,65527688,64877643-65527688,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,100,pl,NaN,g,0001,od,fc,oper,:v:100:pl:g:0001:od:fc:oper
88,89,66614387,67122891,66614387-67122891,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,925,pl,NaN,g,0001,od,fc,oper,:gh:925:pl:g:0001:od:fc:oper
90,91,68201033,68853778,68201033-68853778,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,2t,NaN,sfc,NaN,g,0001,od,fc,oper,:2t:sfc:g:0001:od:fc:oper
91,92,68853778,69519548,68853778-69519548,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,100,pl,NaN,g,0001,od,fc,oper,:u:100:pl:g:0001:od:fc:oper
98,99,74759598,75348271,74759598-75348271,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,925,pl,NaN,g,0001,od,fc,oper,:t:925:pl:g:0001:od:fc:oper
100,101,76201966,76748026,76201966-76748026,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,1000,pl,NaN,g,0001,od,fc,oper,:gh:1000:pl:g:0001:od:fc:oper
101,102,76748026,77468782,76748026-77468782,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,600,pl,NaN,g,0001,od,fc,oper,:v:600:pl:g:0001:od:fc:oper
102,103,77468782,78167699,77468782-78167699,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,600,pl,NaN,g,0001,od,fc,oper,:u:600:pl:g:0001:od:fc:oper
107,108,82193999,82798699,82193999-82798699,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,50,pl,NaN,g,0001,od,fc,oper,:v:50:pl:g:0001:od:fc:oper
108,109,82798699,83404273,82798699-83404273,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,1000,pl,NaN,g,0001,od,fc,oper,:t:1000:pl:g:0001:od:fc:oper
109,110,83404273,84036339,83404273-84036339,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,50,pl,NaN,g,0001,od,fc,oper,:u:50:pl:g:0001:od:fc:oper
111,112,85402132,85883550,85402132-85883550,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,700,pl,NaN,g,0001,od,fc,oper,:gh:700:pl:g:0001:od:fc:oper
117,118,90149359,90557372,90149359-90557372,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,500,pl,NaN,g,0001,od,fc,oper,:gh:500:pl:g:0001:od:fc:oper
118,119,90557372,91211699,90557372-91211699,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,700,pl,NaN,g,0001,od,fc,oper,:t:700:pl:g:0001:od:fc:oper
120,121,92351206,92999142,92351206-92999142,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,300,pl,NaN,g,0001,od,fc,oper,:v:300:pl:g:0001:od:fc:oper
121,122,92999142,93614535,92999142-93614535,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,300,pl,NaN,g,0001,od,fc,oper,:u:300:pl:g:0001:od:fc:oper
124,125,95858290,96472946,95858290-96472946,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,500,pl,NaN,g,0001,od,fc,oper,:t:500:pl:g:0001:od:fc:oper
126,127,97895581,98609780,97895581-98609780,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,200,pl,NaN,g,0001,od,fc,oper,:v:200:pl:g:0001:od:fc:oper
127,128,98609780,99311559,98609780-99311559,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,200,pl,NaN,g,0001,od,fc,oper,:u:200:pl:g:0001:od:fc:oper
131,132,101748643,102185605,101748643-102185605,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,400,pl,NaN,g,0001,od,fc,oper,:gh:400:pl:g:0001:od:fc:oper
135,136,106192299,106653051,106192299-106653051,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,250,pl,NaN,g,0001,od,fc,oper,:gh:250:pl:g:0001:od:fc:oper
136,137,106653051,107257775,106653051-107257775,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,400,pl,NaN,g,0001,od,fc,oper,:t:400:pl:g:0001:od:fc:oper
137,138,107257775,107993378,107257775-107993378,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,925,pl,NaN,g,0001,od,fc,oper,:v:925:pl:g:0001:od:fc:oper
139,140,108453896,109171779,108453896-109171779,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,925,pl,NaN,g,0001,od,fc,oper,:u:925:pl:g:0001:od:fc:oper
143,144,112538957,113080902,112538957-113080902,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,sp,NaN,sfc,NaN,g,0001,od,fc,oper,:sp:sfc:g:0001:od:fc:oper
144,145,113080902,113701913,113080902-113701913,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,250,pl,NaN,g,0001,od,fc,oper,:t:250:pl:g:0001:od:fc:oper
147,148,115589782,116428222,115589782-116428222,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,1000,pl,NaN,g,0001,od,fc,oper,:u:1000:pl:g:0001:od:fc:oper
151,152,118818632,119655550,118818632-119655550,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,1000,pl,NaN,g,0001,od,fc,oper,:v:1000:pl:g:0001:od:fc:oper
155,156,122734816,123456734,122734816-123456734,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,v,700,pl,NaN,g,0001,od,fc,oper,:v:700:pl:g:0001:od:fc:oper
156,157,123456734,124157221,123456734-124157221,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,u,700,pl,NaN,g,0001,od,fc,oper,:u:700:pl:g:0001:od:fc:oper
157,158,124157221,124601968,124157221-124601968,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,gh,150,pl,NaN,g,0001,od,fc,oper,:gh:150:pl:g:0001:od:fc:oper
159,160,125964113,126569022,125964113-126569022,2026-01-23,2026-01-23 06:00:00,0 days 06:00:00,t,150,pl,NaN,g,0001,od,fc,oper,:t:150:pl:g:0001:od:fc:oper

In [57]:
fp = H.download(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

In [58]:
ds = xr.open_dataset(fp)
ds

skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))

<xarray.Dataset> Size: 237MB
Dimensions:            (latitude: 721, longitude: 1440, isobaricInhPa: 13)
Coordinates:
  * latitude           (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude          (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * isobaricInhPa      (isobaricInhPa) float64 104B 1e+03 925.0 ... 100.0 50.0
    time               datetime64[ns] 8B ...
    step               timedelta64[ns] 8B ...
    heightAboveGround  float64 8B ...
    valid_time         datetime64[ns] 8B ...
    surface            float64 8B ...
Data variables:
    fg10               (latitude, longitude) float32 4MB ...
    gh                 (isobaricInhPa, latitude, longitude) float32 54MB ...
    t                  (isobaricInhPa, latitude, longitude) float32 54MB ...
    u                  (isobaricInhPa, latitude, longitude) float32 54MB ...
    v                  (isobaricInhPa, latitude, longitude) float32 54MB ...
    tp                 (latitude, longitude) float32 4MB ...
    sd                 (latitude, longitude) float32 4MB ...
    ptype              (latitude, longitude) float32 4MB ...
    sp                 (latitude, longitude) float32 4MB ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-03-23T16:07 GRIB to CDM+CF via cfgrib-0.9.1...

In [59]:
H = FastHerbie([run], model="ifs", product="oper", fxx=np.arange(0,102,6).tolist(), save_dir='./data/', overwrite=True)

In [60]:
H.inventory(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

,grib_message,start_byte,end_byte,range,reference_time,valid_time,step,param,levelist,levtype,number,domain,expver,class,type,stream,search_this,FILE
0,8,3841534,4871060,3841534-4871060,2026-01-23,2026-01-23,0 days,ptype,NaN,sfc,NaN,g,0001,od,fc,oper,:ptype:sfc:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
1,17,8320627,8749643,8320627-8749643,2026-01-23,2026-01-23,0 days,gh,100,pl,NaN,g,0001,od,fc,oper,:gh:100:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
2,19,8749867,9485485,8749867-9485485,2026-01-23,2026-01-23,0 days,v,500,pl,NaN,g,0001,od,fc,oper,:v:500:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
3,24,13202368,13913549,13202368-13913549,2026-01-23,2026-01-23,0 days,u,500,pl,NaN,g,0001,od,fc,oper,:u:500:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
4,25,13913549,14400876,13913549-14400876,2026-01-23,2026-01-23,0 days,gh,850,pl,NaN,g,0001,od,fc,oper,:gh:850:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,154,122150785,122584169,122150785-122584169,2026-01-23,2026-01-27,4 days,gh,150,pl,NaN,g,0001,od,fc,oper,:gh:150:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
981,155,122584169,123123438,122584169-123123438,2026-01-23,2026-01-27,4 days,sp,NaN,sfc,NaN,g,0001,od,fc,oper,:sp:sfc:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
982,156,123123438,123817050,123123438-123817050,2026-01-23,2026-01-27,4 days,u,700,pl,NaN,g,0001,od,fc,oper,:u:700:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
983,158,125163568,125877302,125163568-125877302,2026-01-23,2026-01-27,4 days,v,700,pl,NaN,g,0001,od,fc,oper,:v:700:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...
984,160,126547272,127144183,126547272-127144183,2026-01-23,2026-01-27,4 days,t,150,pl,NaN,g,0001,od,fc,oper,:t:150:pl:g:0001:od:fc:oper,https://storage.googleapis.com/ecmwf-open-data...

In [61]:
filepath = H.download(ss)

/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)
/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/herbie/core.py:978: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  logic = df.search_this.str.contains(search)

In [62]:
filepath

[PosixPath('data/ifs/20260123/subset_a9436f37__20260123000000-60h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a9ef4661__20260123000000-0h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a960a5e6__20260123000000-30h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a90ef47f__20260123000000-24h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a932c33f__20260123000000-66h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a9079e51__20260123000000-96h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a9f1444a__20260123000000-72h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a90e36e3__20260123000000-36h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a92632d3__20260123000000-90h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a95e5ee3__20260123000000-78h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a9894b7b__20260123000000-18h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a9e7942f__20260123000000-42h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a9b21df8__20260123000000-6h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a905e411__20260123000000-84h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a978e871__20260123000000-54h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a912e924__20260123000000-12h-oper-fc.grib2'),
 PosixPath('data/ifs/20260123/subset_a91cb9bf__20260123000000-48h-oper-fc.grib2')]

In [63]:
ds = xr.open_mfdataset(filepath, combine='nested', concat_dim='valid_time')

skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
Ignoring index file '/courses/meteo473/sp26/473_sp26_group6/data/ifs/20260123/subset_a9b21df8__20260123000000-6h-oper-fc.grib2.5b7b6.idx' older than GRIB file
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
skipping variable: paramId==167 shortName='t2m'
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 726, in build_dataset_components
    dict_merge(variables, coord_vars)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/anaconda3/envs/custom_envs/meteo473_sp26/lib/python3.13/site-packages/cfgrib/dataset.py", line 642, in dict_merge
    raise DatasetBuildError(
    ...<2 lines>...
    )
cfgrib.dataset.DatasetBuildError: key present and new value is different: key='heightAboveGround' value=Variable(dimensions=(), data=np.float64(10.0)) new_value=Variable(dimensions=(), data=np.float64(2.0))
/tmp/ipykernel_1100054/820905488.py:1: FutureWarning: In a future version of xarray the default value for coords will change from coords='different' to coords='minimal'. This is likely to lead to different results when multiple datasets have matching variables with overlapping values. To opt in to new defaults and get rid of these warnings now use `set_options(use_new_combine_kwarg_defaults=True) or set coords explicitly.
  ds = xr.open_mfdataset(filepath, combine='nested', concat_dim='valid_time')

In [64]:
ds

<xarray.Dataset> Size: 4GB
Dimensions:            (valid_time: 17, latitude: 721, longitude: 1440,
                        isobaricInhPa: 13)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 136B 2026-01-25T12:00:00 ....
  * latitude           (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude          (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * isobaricInhPa      (isobaricInhPa) float64 104B 1e+03 925.0 ... 100.0 50.0
    time               datetime64[ns] 8B 2026-01-23
    step               (valid_time) timedelta64[ns] 136B 2 days 12:00:00 ... ...
    heightAboveGround  (valid_time) float64 136B 10.0 10.0 10.0 ... 10.0 10.0
    surface            float64 8B 0.0
Data variables:
    fg10               (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    sd                 (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    t                  (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    tp                 (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    gh                 (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    v                  (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    u                  (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    ptype              (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    sp                 (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    t2m                (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-03-23T16:07 GRIB to CDM+CF via cfgrib-0.9.1...

In [65]:
ds = ds.sortby('valid_time')
ds

<xarray.Dataset> Size: 4GB
Dimensions:            (valid_time: 17, latitude: 721, longitude: 1440,
                        isobaricInhPa: 13)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 136B 2026-01-23 ... 2026-0...
  * latitude           (latitude) float64 6kB 90.0 89.75 89.5 ... -89.75 -90.0
  * longitude          (longitude) float64 12kB -180.0 -179.8 ... 179.5 179.8
  * isobaricInhPa      (isobaricInhPa) float64 104B 1e+03 925.0 ... 100.0 50.0
    time               datetime64[ns] 8B 2026-01-23
    step               (valid_time) timedelta64[ns] 136B 0 days 00:00:00 ... ...
    heightAboveGround  (valid_time) float64 136B 10.0 10.0 10.0 ... 10.0 2.0
    surface            float64 8B 0.0
Data variables:
    fg10               (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    sd                 (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    t                  (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    tp                 (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    gh                 (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    v                  (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    u                  (valid_time, isobaricInhPa, latitude, longitude) float32 918MB dask.array<chunksize=(1, 13, 721, 1440), meta=np.ndarray>
    ptype              (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    sp                 (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
    t2m                (valid_time, latitude, longitude) float32 71MB dask.array<chunksize=(1, 721, 1440), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-03-23T16:07 GRIB to CDM+CF via cfgrib-0.9.1...

In [66]:
ds = ds.sel(latitude=slice(60,20), longitude=slice(-130,-60))
ds

<xarray.Dataset> Size: 178MB
Dimensions:            (valid_time: 17, latitude: 161, longitude: 281,
                        isobaricInhPa: 13)
Coordinates:
  * valid_time         (valid_time) datetime64[ns] 136B 2026-01-23 ... 2026-0...
  * latitude           (latitude) float64 1kB 60.0 59.75 59.5 ... 20.25 20.0
  * longitude          (longitude) float64 2kB -130.0 -129.8 ... -60.25 -60.0
  * isobaricInhPa      (isobaricInhPa) float64 104B 1e+03 925.0 ... 100.0 50.0
    time               datetime64[ns] 8B 2026-01-23
    step               (valid_time) timedelta64[ns] 136B 0 days 00:00:00 ... ...
    heightAboveGround  (valid_time) float64 136B 10.0 10.0 10.0 ... 10.0 2.0
    surface            float64 8B 0.0
Data variables:
    fg10               (valid_time, latitude, longitude) float32 3MB dask.array<chunksize=(1, 161, 281), meta=np.ndarray>
    sd                 (valid_time, latitude, longitude) float32 3MB dask.array<chunksize=(1, 161, 281), meta=np.ndarray>
    t                  (valid_time, isobaricInhPa, latitude, longitude) float32 40MB dask.array<chunksize=(1, 13, 161, 281), meta=np.ndarray>
    tp                 (valid_time, latitude, longitude) float32 3MB dask.array<chunksize=(1, 161, 281), meta=np.ndarray>
    gh                 (valid_time, isobaricInhPa, latitude, longitude) float32 40MB dask.array<chunksize=(1, 13, 161, 281), meta=np.ndarray>
    v                  (valid_time, isobaricInhPa, latitude, longitude) float32 40MB dask.array<chunksize=(1, 13, 161, 281), meta=np.ndarray>
    u                  (valid_time, isobaricInhPa, latitude, longitude) float32 40MB dask.array<chunksize=(1, 13, 161, 281), meta=np.ndarray>
    ptype              (valid_time, latitude, longitude) float32 3MB dask.array<chunksize=(1, 161, 281), meta=np.ndarray>
    sp                 (valid_time, latitude, longitude) float32 3MB dask.array<chunksize=(1, 161, 281), meta=np.ndarray>
    t2m                (valid_time, latitude, longitude) float32 3MB dask.array<chunksize=(1, 161, 281), meta=np.ndarray>
Attributes:
    GRIB_edition:            2
    GRIB_centre:             ecmf
    GRIB_centreDescription:  European Centre for Medium-Range Weather Forecasts
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             European Centre for Medium-Range Weather Forecasts
    history:                 2026-03-23T16:07 GRIB to CDM+CF via cfgrib-0.9.1...

In [68]:
fname = f'ecmwf_update.nc'
ds.to_netcdf(fname)

PermissionError: [Errno 13] Permission denied: '/courses/meteo473/sp26/473_sp26_group6/ecmwf_update.nc'

In [69]:
ds_test = xr.open_dataset(fname)
ds_test

ValueError: did not find a match in any of xarray's currently installed IO backends ['netcdf4', 'h5netcdf', 'scipy', 'cfgrib', 'cfradial1', 'datamet', 'furuno', 'gamic', 'gini', 'hpl', 'iris', 'metek', 'nexradlevel2', 'odim', 'rainbow', 'uf']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html